# Meta

env: "production"
docs_file: "website.min"

# Build

markdown: kramdown
permalink: pretty
# url: https://bulma.io
url: http://127.0.0.1:4000
exclude:
  [
    ".babelrc",
    "docker-compose.yml",
    "icons",
    "node_modules",
    "package.json",
    "templates",
    "website.scss",
    "yarn.lock",
  ]
